'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, FlaskConical, MoveRight } from 'lucide-react';
import SiteNav from '../site-nav';
import { getScenario, periods, type Period } from '../city-insights-data';
import '../city-insights.css';
export default function Page() {
  const [period, setPeriod] = useState<Period>('peak');
  const [selectedId, setSelectedId] = useState('times');
  const rows = getScenario(period);
  const selected = rows.find(row => row.id === selectedId)!;
  return <div className="city-insights"><SiteNav/><main className="ci-main">
    <div className="ci-breadcrumb"><a href="/">ExitNow</a><span>/</span><span>City insights</span><a href="/operations">Operations <ArrowUpRight size={15}/></a></div>
    <header className="ci-header"><h1>A better city.<br/><span>One bottleneck at a time.</span></h1><div><p>See where the journey slows down.<br/>Explore small changes that could make a big difference.</p><span className="ci-demo"><FlaskConical size={15}/> Synthetic data · demonstration</span></div></header>
    <section className="ci-workbench" aria-labelledby="bottlenecks-heading">
      <div className="ci-toolbar"><div><h2 id="bottlenecks-heading">Where New York gets stuck</h2><p>Six sample stations. A citywide conversation.</p></div><div className="ci-filters" role="group" aria-label="Scenario period">{(Object.keys(periods) as Period[]).map(key => <button key={key} aria-pressed={period === key} onClick={() => setPeriod(key)}>{periods[key].label}</button>)}</div></div>
      <div className="ci-analysis"><div className="ci-chart"><div className="ci-chart-label"><span>Modeled extra minutes per rider</span><span>{periods[period].hours}</span></div><div className="ci-axis" aria-hidden="true"><span>0</span><span>2.5 min</span><span>5 min</span></div><div className="ci-bars">{rows.map((row, index) => <button key={row.id} className={`ci-station${selectedId === row.id ? ' ci-selected' : ''}`} aria-pressed={selectedId === row.id} onClick={() => setSelectedId(row.id)}><span className="ci-station-name"><span className="ci-rank">{String(index + 1).padStart(2, '0')}</span><span>{row.name}<small>{row.borough} · {row.issue}</small></span><strong>{row.delayMinutes.toFixed(1)}<small>min</small></strong></span><span className="ci-track" aria-hidden="true"><span style={{width: `${row.delayMinutes / 5 * 100}%`}}/></span></button>)}</div><p className="ci-chart-note">Select a station to explore an improvement. Rankings reflect this illustrative scenario only.</p></div>
      <aside className="ci-detail" aria-live="polite" aria-atomic="true"><div className="ci-detail-top"><span>Station in focus</span><ArrowUpRight size={23}/></div><h2>{selected.name}</h2><div className="ci-lines" aria-label={`Subway lines ${selected.lines.join(', ')}`}>{selected.lines.map(line => <span key={line}>{line}</span>)}</div><p className="ci-description">{selected.detail}</p><div className="ci-detail-stats"><div><strong>{selected.delayMinutes.toFixed(1)}<small> min</small></strong><span>extra time / rider</span></div><div><strong>{(selected.ridersPerHour / 1000).toFixed(1)}<small>k</small></strong><span>modeled riders / hour</span></div></div><div className="ci-opportunity"><span>Proposed pilot</span><h3>{selected.idea}</h3><p>{selected.action}</p><div className="ci-impact"><span>{selected.delayMinutes.toFixed(1)} min</span><MoveRight size={23}/><strong>{(selected.delayMinutes-selected.savedMinutes).toFixed(1)} min</strong></div><small>Illustrative result if the assumed {Math.round(selected.reduction * 100)}% reduction is achieved. Not a forecast.</small></div><div className="ci-owner">Suggested team <strong>{selected.owner}</strong></div></aside></div>
    </section>
    <section className="ci-next"><div><h2>Better journeys start<br/>with better questions.</h2><p>Which interventions help? Who benefits? What should we measure next? Use these scenarios to frame a pilot, then validate with real station observations.</p></div><a href="/operations">Explore operations <ArrowRight size={21}/></a><a href="/app">Plan your own journey <ArrowUpRight size={21}/></a></section>
    <details className="ci-method"><summary>About this demonstration and its assumptions</summary><p>All passenger counts, delays, bottleneck descriptions and improvement estimates are invented for this interactive prototype. Station names and subway line labels provide geographic context; this is not an MTA performance assessment, live service information, or an accessibility audit. The sample covers six stations, not the complete network.</p><p>Extra time represents an assumed average circulation delay per rider, separate from scheduled train travel. Counts represent hypothetical hourly station throughput. Each period uses a fixed, reproducible scenario. The proposed after-pilot delay equals the scenario delay minus the assumed reduction, rounded to one decimal minute. Real recommendations require observation, engineering review and consultation with riders.</p></details>
    <footer className="ci-footer"><span>ExitNow · A better way through.</span><span>New York City / Urban mobility lab</span></footer>
  </main></div>;
}
