import {createServer,type IncomingMessage} from 'node:http';
import {randomUUID} from 'node:crypto';
import {operatorAuthorized,enrollConsent,deleteTrip} from './operator.ts';
import {Bridge} from './service.ts';
import type {Store} from './store.ts';
async function body(req:IncomingMessage):Promise<Record<string,unknown>>{let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>16384)throw Error('request too large');}const value=JSON.parse(raw||'{}');if(!value||Array.isArray(value)||typeof value!=='object')throw Error('invalid input');return value;}
export function createReplayBridge(store:Store,rewards?:Bridge['rewards']){let bridge:Bridge;bridge=new Bridge(store,{async send(){}},async j=>{const result=await bridge.tool(j.id,j.token,'plan_route',{...(j.fixture??{origin:'columbia',destination:'williamsburg',departureTime:'2026-09-26T22:00:00Z'})}) as {recommended:{nextInstruction:string;arrivalRange:[string,string]}};await bridge.tool(j.id,j.token,'complete_job',{text:`Replay — ${result.recommended.nextInstruction} Arrival window ${result.recommended.arrivalRange.join(' – ')}. Synthetic timetable; no live iMessage sent.`});},rewards);return bridge;}
export function createGatewayServer(bridge:Bridge,replay:boolean){return createServer(async(req,res)=>{res.setHeader('content-type','application/json');try{
 if(req.method==='GET'&&req.url==='/health'){res.end(JSON.stringify({status:'ok',mode:replay?'replay':'live',durable:true}));return;}
 if(replay&&req.method==='GET'&&req.url==='/replay/state'){const view=await bridge.store.transaction(s=>({mode:'replay',jobs:s.jobs.map(({token,...j})=>j),trips:Object.values(s.trips).map(t=>({id:t.id,version:t.version,route:t.route,arrived:t.arrived})),outbox:s.outbox}));res.end(JSON.stringify(view));return;}
 if(replay&&req.method==='POST'&&req.url==='/replay/messages'){const data=await body(req);if(typeof data.text!=='string'||data.text.length>3000)throw Error('text required, up to 3000 characters');const result=await bridge.receive({eventId:typeof data.eventId==='string'?data.eventId:randomUUID(),tripId:'replay-trip',sender:'replay-rider',spaceId:'replay-dm',text:data.text,timestamp:Date.now(),fixture:{origin:typeof data.origin==='string'?data.origin:'columbia',destination:typeof data.destination==='string'?data.destination:'williamsburg',departureTime:typeof data.departureTime==='string'?data.departureTime:'2026-09-26T22:00:00Z'}});res.writeHead(202);res.end(JSON.stringify({...result,mode:'replay'}));return;}
 const admin=req.url?.match(/^\/operator\/trips\/([^/]+)(?:\/(consent))?$/);if(admin){if(!operatorAuthorized(req.headers.authorization,process.env.GATEWAY_OPERATOR_SECRET)){res.writeHead(403);res.end(JSON.stringify({error:'operator authorization required'}));return;}const id=decodeURIComponent(admin[1]);if(req.method==='POST'&&admin[2]){const input=await body(req);res.end(JSON.stringify(await bridge.store.transaction(s=>enrollConsent(s,id,input))));return;}if(req.method==='DELETE'&&!admin[2]){res.end(JSON.stringify(await bridge.store.transaction(s=>deleteTrip(s,id))));return;}res.writeHead(405);res.end('{}');return;}
 const match=req.url?.match(/^\/jobs\/([a-f0-9-]+)\/tools\/([a-z_]+)$/);if(req.method!=='POST'||!match){res.writeHead(404);res.end('{}');return;}const data=await body(req),token=req.headers.authorization?.replace(/^Bearer /,'')??'';res.end(JSON.stringify(await bridge.tool(match[1],token,match[2],data)));
 }catch(e){res.writeHead(400);res.end(JSON.stringify({error:e instanceof Error?e.message:'request failed'}));}});}
