import {getRewardsService} from '../../../packages/rewards/src/runtime.ts';
import {MongoClient} from 'mongodb';
import {Bridge} from './service.ts';
import {MongoStore,FileReplayStore} from './store.ts';
import {photon,dispatchGrok} from './providers.ts';
import {createGatewayServer,createReplayBridge} from './http.ts';
const replay=process.env.GATEWAY_MODE==='replay';
if(!replay&&!process.env.MONGODB_URI)throw Error('MONGODB_URI required. Set GATEWAY_MODE=replay explicitly for local replay.');
const client=replay?undefined:new MongoClient(process.env.MONGODB_URI!);
if(client)await client.connect();
const store=replay?new FileReplayStore(process.env.GATEWAY_REPLAY_FILE??'.data/gateway-replay.json'):new MongoStore(client!,process.env.MONGODB_DB??'exitnow');
if(store instanceof MongoStore){await store.initialize();await store.transaction(()=>true);}else await store.load();
let bridge:Bridge;
const transport=replay?undefined:await photon(e=>bridge.receive(e));
bridge=replay?createReplayBridge(store,getRewardsService):new Bridge(store,transport!.messenger,dispatchGrok,getRewardsService);
let busy=false;const timer=setInterval(async()=>{if(busy)return;busy=true;try{await bridge.tick();}catch{console.error('Gateway worker failed; inspect database/provider availability');}finally{busy=false;}},1000);
const server=createGatewayServer(bridge,replay);server.listen(Number(process.env.GATEWAY_PORT??8787),replay?'127.0.0.1':'0.0.0.0');
transport?.reader.catch(()=>{console.error('Photon stream terminated');process.exitCode=1;server.close();clearInterval(timer);});
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{clearInterval(timer);server.close();void transport?.stop();void client?.close();});
