import {test} from 'node:test';
import assert from 'node:assert/strict';
import type {MongoClient} from 'mongodb';
import {MongoStateRepository} from '../src/index.js';
const tagged=(name:string)=>Object.assign(Error(name),{hasErrorLabel:(label:string)=>label===name});
function fake(options:{lockFailures?:number;commitFailures?:number;saveFailure?:boolean}={}){const events:string[]=[];let locks=options.lockFailures??0,commits=options.commitFailures??0;let state={n:0};const collection={updateOne:async(_q:unknown,update:any)=>{if(update.$setOnInsert){events.push('initialize');return {matchedCount:1}}events.push('save');if(options.saveFailure)throw tagged('TransientTransactionError');state=update.$set.state;return {matchedCount:1}},findOneAndUpdate:async()=>{events.push('lock');if(locks-->0)throw tagged('TransientTransactionError');return {_id:'state',revision:1,state}}};const client={db:()=>({collection:()=>collection}),startSession:()=>({startTransaction:()=>events.push('start'),inTransaction:()=>true,abortTransaction:async()=>{events.push('abort')},endSession:async()=>{events.push('end')},commitTransaction:async()=>{events.push('commit');if(commits-->0)throw tagged('UnknownTransactionCommitResult')}})} as unknown as MongoClient;return {repo:new MongoStateRepository(client,'test','state',{n:0}),events}}
test('write acquisition precedes callback; pre-callback conflict can retry',async()=>{const x=fake({lockFailures:1});await x.repo.initialize();let callbacks=0;await x.repo.transact(async s=>{callbacks++;x.events.push('callback');s.n++});assert.equal(callbacks,1);assert.equal(x.events.filter(x=>x==='lock').length,2);assert.ok(x.events.indexOf('callback')>x.events.lastIndexOf('lock'))});
test('unknown commit retries commit only',async()=>{const x=fake({commitFailures:2});let callbacks=0;await x.repo.transact(async()=>{callbacks++});assert.equal(callbacks,1);assert.equal(x.events.filter(x=>x==='commit').length,3)});
test('post-callback transient failure never replays callback',async()=>{const x=fake({saveFailure:true});let callbacks=0;await assert.rejects(x.repo.transact(async()=>{callbacks++}));assert.equal(callbacks,1);assert.equal(x.events.filter(x=>x==='lock').length,1)});
test('unknown commit eventually fails closed without callback replay',async()=>{const x=fake({commitFailures:10});let callbacks=0;await assert.rejects(x.repo.transact(async()=>{callbacks++}));assert.equal(callbacks,1);assert.equal(x.events.filter(x=>x==='commit').length,3)});
