export type Mode = 'replay'|'live'|'stale';
export interface Station {id:string;name:string;lat:number;lon:number;accessible:'yes'|'no'|'unknown';neighborhood:string}
export interface Edge {from:string;to:string;line:string;direction:string;minutes:number;headway:number;offset?:number;walk?:boolean;accessible?:boolean;days?:number[];firstMinute?:number;lastMinute?:number;continuationId?:string}
export interface Network {stations:Station[];edges:Edge[];mode:Mode;sourceTimestamp:string;source:string}
export interface RouteRequest {origin:string;destination:string;departureTime:string;preferFewerTransfers?:boolean;maxWalkMinutes?:number;requireAccessible?:boolean;blockedLines?:string[]}
export interface Leg {from:string;to:string;fromName:string;toName:string;line:string;direction:string;departureTime:string;arrivalTime:string;walk:boolean;minutes:number;continuationId?:string}
export interface Journey {legs:Leg[];departureTime:string;arrivalTime:string;arrivalRange:[string,string];durationMinutes:number;transfers:number;nextInstruction:string}
export interface RoutePlan {recommended:Journey;alternative:Journey|null;freshness:{mode:Mode;sourceTimestamp:string;stale:boolean};warnings:string[]}
const iso=(n:number)=>new Date(n).toISOString();
const stations:Station[]=[['columbia','116 St–Columbia',40.807,-73.964,'Morningside Heights'],['times-square','Times Square',40.755,-73.987,'Midtown'],['union-square','Union Square',40.735,-73.99,'Union Square'],['williamsburg','Bedford Avenue',40.718,-73.957,'Williamsburg'],['queens','Court Square',40.747,-73.946,'Long Island City'],['brooklyn','Hoyt–Schermerhorn',40.689,-73.985,'Downtown Brooklyn']].map(([id,name,lat,lon,neighborhood])=>({id:String(id),name:String(name),lat:Number(lat),lon:Number(lon),neighborhood:String(neighborhood),accessible:'unknown'}));
const pair=(from:string,to:string,line:string,minutes:number,headway:number,direction:string):Edge[]=>[{from,to,line,minutes,headway,direction,continuationId:line+':forward'},{from:to,to:from,line,minutes,headway,continuationId:line+':reverse',direction:direction==='southbound'?'northbound':'opposite direction'}];
export const demoNetwork:Network={stations,mode:'replay',sourceTimestamp:'2026-09-26T22:00:00Z',source:'Synthetic demonstration timetable. Not MTA service predictions.',edges:[...pair('columbia','times-square','1',20,8,'southbound'),...pair('times-square','union-square','N',9,7,'downtown'),...pair('union-square','williamsburg','L',12,6,'Brooklyn-bound'),...pair('times-square','queens','7',15,6,'Queens-bound'),...pair('queens','williamsburg','G',22,10,'Brooklyn-bound'),...pair('williamsburg','brooklyn','G',20,10,'southbound'),...pair('union-square','brooklyn','N',22,7,'Brooklyn-bound')]};
function stationId(value:string,network:Network):string {const text=value.toLowerCase();const found=network.stations.find(s=>s.id===text||s.name.toLowerCase()===text||s.name.toLowerCase().includes(text));if(!found)throw new Error(`Unknown station: ${value}. Confirm a supported station.`);return found.id;}
export function planRoute(request:RouteRequest,network:Network=demoNetwork):RoutePlan {
 const start=Date.parse(request.departureTime);if(!Number.isFinite(start))throw new Error('Invalid departureTime');
 const origin=stationId(request.origin,network),destination=stationId(request.destination,network);if(origin===destination)throw new Error('Origin and destination must differ');
 const lookup=new Map(network.stations.map(s=>[s.id,s]));
 const paths:Journey[]=[];
 function visit(at:string,time:number,legs:Leg[],seen:Set<string>,walking:number){if(paths.length>5000)return;if(at===destination){const transfers=Math.max(0,legs.reduce((a,l,i)=>a+(!l.walk&&(i===0||legs[i-1].walk||!l.continuationId||legs[i-1].continuationId!==l.continuationId)?1:0),0)-1);paths.push({legs,departureTime:iso(start),arrivalTime:iso(time),arrivalRange:[iso(time),iso(time+(network.mode==='replay'?4:8)*60000)],durationMinutes:(time-start)/60000,transfers,nextInstruction:`${legs[0].walk?'Walk':'Take '+legs[0].line+' '+legs[0].direction} from ${legs[0].fromName} to ${legs[0].toName}. Confirm your station before boarding.`});return;}
 for(const e of network.edges.filter(e=>e.from===at)){if(seen.has(e.to)||request.blockedLines?.includes(e.line))continue;const to=lookup.get(e.to)!,from=lookup.get(e.from)!;if(request.requireAccessible&&(to.accessible!=='yes'||from.accessible!=='yes'||e.accessible!==true))continue;const walk=walking+(e.walk?e.minutes:0);if(walk>(request.maxWalkMinutes??20))continue;
 // Timetable fixture uses America/New_York service-day local minutes, independent of host TZ.
 const local=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(time);const part=(type:string)=>local.find(p=>p.type===type)?.value||'';const day=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(part('weekday'));const minute=Number(part('hour'))*60+Number(part('minute'))+(time%60000)/60000;if(e.days&&!e.days.includes(day))continue;
 const previous=legs.at(-1);
 const continuing=!!e.continuationId&&!e.walk&&!previous?.walk&&previous?.continuationId===e.continuationId;
 const change=previous&&!continuing&&!e.walk?3:0;
 const earliest=Math.max(minute+change,e.firstMinute??0);
 const headway=e.headway||1, offset=e.offset??0;
 const departureMinute=e.walk||continuing?minute:offset+Math.ceil((earliest-offset)/headway)*headway;
 if(!continuing&&!e.walk&&departureMinute>(e.lastMinute??1440))continue;
 const departure=time+(departureMinute-minute)*60000;const arrival=departure+e.minutes*60000;
 visit(e.to,arrival,[...legs,{from:e.from,to:e.to,fromName:from.name,toName:to.name,line:e.line,direction:e.direction,departureTime:iso(departure),arrivalTime:iso(arrival),walk:!!e.walk,minutes:e.minutes,continuationId:e.continuationId}],new Set([...seen,e.to]),walk);
 }}
 visit(origin,start,[],new Set([origin]),0);paths.sort((a,b)=>(a.durationMinutes+a.transfers*(request.preferFewerTransfers?12:2))-(b.durationMinutes+b.transfers*(request.preferFewerTransfers?12:2)));if(!paths.length)throw new Error('No route satisfies the confirmed constraints. Accessibility may be unknown.');const stale=network.mode!=='replay'&&start-Date.parse(network.sourceTimestamp)>90000;
 return {recommended:paths[0],alternative:paths[1]??null,freshness:{mode:stale?'stale':network.mode,sourceTimestamp:network.sourceTimestamp,stale},warnings:[...(network.mode==='replay'?['Synthetic replay: schedules, travel times, and arrival ranges are demo assumptions.']:[]),...(stale?['Realtime data is stale; this itinerary uses timetable assumptions.']:[]),...(!request.requireAccessible?['Accessibility is unverified. No station exit or train position is inferred.']:[])]};
}
export interface Progress {station:string;updatedAt:string;status:'active'|'arrived';}
export function confirmProgress(state:Progress,event:{kind:'missed_train'|'wrong_train'|'at_station'|'arrived';station?:string},now:string):Progress{if(Date.parse(now)<Date.parse(state.updatedAt))throw new Error('Outdated progress');if((event.kind==='wrong_train'||event.kind==='at_station')&&!event.station)throw new Error('Confirm the current station to reroute');return {...state,station:event.station??state.station,updatedAt:now,status:event.kind==='arrived'?'arrived':'active'};}
export function affectedByChange(journey:Journey,lines:string[]){return journey.legs.some(l=>lines.includes(l.line));}
export function notificationEligibility(n:{consented:boolean;destinationAllowed:boolean;etaShiftMinutes:number;lastSentAt:number;now:number;incidentId?:string;lastIncidentId?:string;arrival?:boolean;arrivalConfirmed?:boolean;cooldownMs?:number}){const reason=!n.consented?'consent_revoked':!n.destinationAllowed?'destination_not_allowed':n.arrival&&!n.arrivalConfirmed?'arrival_unconfirmed':n.incidentId&&n.incidentId===n.lastIncidentId?'duplicate_incident':n.now-n.lastSentAt<(n.cooldownMs??300000)?'cooldown':!n.arrival&&Math.abs(n.etaShiftMinutes)<5?'below_threshold':'eligible';return {eligible:reason==='eligible',reason};}
export const corridorEvidence={id:'queens-brooklyn',name:'Queens → Brooklyn',type:'synthetic_demonstration',sampleSize:120,timeWindow:'2026-09-26 18:00–19:00 America/New_York',baseline:'Synthetic scheduled route durations',coverage:'Three synthetic origin–destination groups; not representative of NYC riders.',source:'ExitNow fixture v1',uncertainty:'Illustrative assumptions; no observed riders or historical ridership inferred.',neighborhoods:['Long Island City','Williamsburg','Downtown Brooklyn']};
export function compareScenarios(budgetMillions=250){if(!Number.isFinite(budgetMillions)||budgetMillions<0)throw new Error('Invalid budget');const demand=[{origin:'queens',destination:'brooklyn',riders:60},{origin:'queens',destination:'williamsburg',riders:40},{origin:'williamsburg',destination:'brooklyn',riders:20}];const definitions=[{id:'baseline',name:'No change',cost:[0,0],operating:0,apply:(n:Network)=>n},{id:'service',name:'More frequent G service',cost:[2,5],operating:3.5,apply:(n:Network)=>({...n,edges:n.edges.map(e=>e.line==='G'?{...e,headway:4}:e)})},{id:'transfer',name:'Accessible corridor stops',cost:[35,65],operating:0.8,apply:(n:Network)=>({...n,stations:n.stations.map(s=>({...s,accessible:'yes' as const})),edges:n.edges.map(e=>({...e,accessible:true}))})},{id:'connection',name:'Hypothetical direct connection',cost:[150,250],operating:7,apply:(n:Network)=>({...n,edges:[...n.edges,...pair('queens','brooklyn','X',24,6,'Brooklyn-bound')]})}];
 const score=(n:Network,multiplier=1)=>demand.reduce((acc,d)=>{const p=planRoute({...d,departureTime:'2026-09-26T22:03:00Z'},n).recommended;return {hours:acc.hours+p.durationMinutes*d.riders*multiplier/60,transfers:acc.transfers+p.transfers*d.riders*multiplier};},{hours:0,transfers:0});const base=score(demoNetwork);
 const bundles=Array.from({length:8},(_,mask)=>{const selected=definitions.slice(1).filter((_,i)=>mask&(1<<i));const network=selected.reduce((n,d)=>d.apply(n),demoNetwork);const result=score(network);const cost=[selected.reduce((n,d)=>n+d.cost[0],0),selected.reduce((n,d)=>n+d.cost[1],0)];return {id:selected.map(d=>d.id).join('+')||'baseline',interventions:selected.map(d=>d.id),name:selected.map(d=>d.name).join(' + ')||'No change',capitalCostMillions:cost,annualOperatingCostMillions:Number(selected.reduce((n,d)=>n+d.operating,0).toFixed(2)),feasible:cost[1]<=budgetMillions,passengerHours:Number(result.hours.toFixed(2)),passengerHoursSaved:Number((base.hours-result.hours).toFixed(2)),transfers:result.transfers,accessibilityCoverage:selected.some(d=>d.id==='transfer')?1:0};});
 return {evidence:corridorEvidence,demand,bundles,assumptions:['Every scenario reroutes the same 120 synthetic requests.','Capital and annual operating costs are synthetic USD millions, not project estimates.','Passenger-hours are modeled time value, not agency cash savings.','Demand sensitivity ±25%; no induced demand or crowding model.'],scenarios:definitions.map(d=>{const n=d.apply(demoNetwork),s=score(n);const saved=base.hours-s.hours;return {id:d.id,name:d.name,passengerHours:Number(s.hours.toFixed(2)),passengerHoursSaved:Number(saved.toFixed(2)),transfers:s.transfers,accessibilityCoverage:d.id==='transfer'?1:0,capitalCostMillions:d.cost,annualOperatingCostMillions:d.operating,feasible:d.cost[1]<=budgetMillions,sensitivity:{lowDemandHoursSaved:Number((saved*.75).toFixed(2)),highDemandHoursSaved:Number((saved*1.25).toFixed(2))},neighborhoods:corridorEvidence.neighborhoods};})};}
export * from './gtfs.ts';
