import type {Journey,Leg,RoutePlan,RouteRequest} from './index.ts';
import {RealtimeCollector,type RealtimeSnapshot} from './realtime.ts';
/** Platform complexes verified against official supplemented GTFS, retrieved 2026-09-26. */
export const mtaStations=[
 {id:'columbia',name:'116 St–Columbia University',stops:['117']},
 {id:'times-square',name:'Times Sq–42 St',stops:['127','725','902','R16']},
 {id:'union-square',name:'14 St–Union Sq',stops:['635','L03','R20']},
 {id:'williamsburg',name:'Bedford Av',stops:['L08']},
 {id:'queens',name:'Court Sq',stops:['719','F09','G22']},
 {id:'brooklyn',name:'Hoyt–Schermerhorn Sts',stops:['A42']},
];
const base='https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs';
export const mtaSources=[['numbered',''],['ace','-ace'],['bdfm','-bdfm'],['g','-g'],['l','-l'],['nqrw','-nqrw']].map(([id,suffix])=>({id,url:base+suffix,source:'MTA Subway GTFS-Realtime'}));
export interface MtaFeedStatus {id:string;url:string;source:string;sourceTimestamp:string|null;fetchedAt:string|null;stale:boolean;error?:string}
export interface MtaFeed extends MtaFeedStatus {snapshot?:RealtimeSnapshot}
export interface MtaArrival {line:string;tripId:string;feedId:string;sourceTimestamp:string;stopId:string;direction:string;arrivalTime:string}
export interface MtaBoard {stations:{id:string;name:string}[];station:{id:string;name:string};arrivals:MtaArrival[];feeds:MtaFeedStatus[];warnings:string[]}
export class MtaError extends Error {constructor(message:string,public status=422){super(message);}}
const collector=new RealtimeCollector();
export async function collectMtaFeeds(now=Date.now()):Promise<MtaFeed[]> {return Promise.all(mtaSources.map(async source=>{try {const snapshot=await collector.collect(source.url,now);return {...source,snapshot,sourceTimestamp:snapshot.sourceTimestamp===null?null:new Date(snapshot.sourceTimestamp).toISOString(),fetchedAt:new Date(snapshot.fetchedAt).toISOString(),stale:snapshot.stale,...(snapshot.error?{error:snapshot.error}:{})};}catch {return {...source,sourceTimestamp:null,fetchedAt:null,stale:true,error:'MTA feed unavailable; retry after the refresh interval.'};}}));}
export function feedStatuses(feeds:MtaFeed[]):MtaFeedStatus[]{return feeds.map(({snapshot,...status})=>status);}
const station=(id:string)=>{const found=mtaStations.find(s=>s.id===id);if(!found)throw new MtaError('Unknown station. Choose a supported MTA station.',400);return found;};
const fresh=(feed:MtaFeed,now:number)=>!feed.stale&&!feed.error&&!!feed.snapshot&&feed.snapshot.sourceTimestamp!==null&&now-feed.snapshot.sourceTimestamp<=90000&&feed.snapshot.sourceTimestamp<=now+30000;
const iso=(time:number)=>new Date(time).toISOString();
const warnings=['Predictions cover six supported station complexes and transfers between them; this is not full-network routing.','Accessibility and elevator status are unverified.','Predictions can change. Check station signs; platform suffixes indicate GTFS direction, not an inferred train location.'];
interface Prediction {station:string;stopId:string;arrival:number;departure:number;sequence:number}
interface Trip {id:string;feedId:string;line:string;stops:Prediction[];sourceTimestamp:string}
function predictions(feeds:MtaFeed[],now:number):Trip[]{const result:Trip[]=[];for(const feed of feeds.filter(f=>fresh(f,now))){for(const entity of feed.snapshot!.entities){const update=entity.tripUpdate,descriptor=update?.trip;if(!update||!descriptor?.tripId||!descriptor.routeId||['CANCELED','DELETED'].includes(descriptor.scheduleRelationship??''))continue;const stops:Prediction[]=[];for(const [index,stop] of (update.stopTimeUpdate??[]).entries()){if(['SKIPPED','NO_DATA'].includes(stop.scheduleRelationship??''))continue;const stopId=stop.stopId??'';if(!/[NS]$/.test(stopId))continue;const match=mtaStations.find(s=>s.stops.includes(stopId.slice(0,-1)));if(!match)continue;const arrival=Number(stop.arrival?.time??stop.departure?.time)*1000,departure=Number(stop.departure?.time??stop.arrival?.time)*1000;if(!Number.isFinite(arrival)||!Number.isFinite(departure)||departure<arrival||arrival>now+3*3600000)continue;stops.push({station:match.id,stopId,arrival,departure,sequence:stop.stopSequence??index});}stops.sort((a,b)=>a.sequence-b.sequence);result.push({id:feed.id+':'+descriptor.tripId+(descriptor.startDate?':'+descriptor.startDate:''),feedId:feed.id,line:descriptor.routeId,stops,sourceTimestamp:feed.sourceTimestamp!});}}return result;}
const direction=(stopId:string)=>stopId.endsWith('N')?'GTFS northbound':'GTFS southbound';
export function buildMtaBoard(stationId:string,feeds:MtaFeed[],now=Date.now()):MtaBoard{const selected=station(stationId);const arrivals=predictions(feeds,now).flatMap(trip=>trip.stops.filter(s=>s.station===stationId&&s.departure>=now).map(s=>({line:trip.line,tripId:trip.id,feedId:trip.feedId,sourceTimestamp:trip.sourceTimestamp,stopId:s.stopId,direction:direction(s.stopId),arrivalTime:iso(s.arrival>=now?s.arrival:s.departure)}))).sort((a,b)=>a.arrivalTime.localeCompare(b.arrivalTime)).slice(0,12);return {stations:mtaStations.map(({id,name})=>({id,name})),station:{id:selected.id,name:selected.name},arrivals,feeds:feedStatuses(feeds),warnings:[...warnings,...(feeds.some(f=>!fresh(f,now))?['Some feeds are stale or unavailable; those predictions are excluded.']:[])]};}
/** Official transfer minima between curated complexes, using a conservative three-minute minimum for same-platform changes. */
function transferSeconds(from:string,to:string){const a=from.slice(0,-1),b=to.slice(0,-1);return (a==='719'&&b==='F09')||(a==='F09'&&b==='719')||(a==='725'&&b==='902')||(a==='902'&&b==='725')?300:180;}
export function validateMtaRequest(request:RouteRequest,now=Date.now()){station(request.origin);station(request.destination);if(request.origin===request.destination)throw new MtaError('Origin and destination must differ.',400);const start=Date.parse(request.departureTime);if(!Number.isFinite(start)||start<now-60000||start>now+5*60000)throw new MtaError('Live departure must be within five minutes of now.',400);if(request.requireAccessible)throw new MtaError('Accessibility cannot be verified from these feeds. No accessible itinerary is offered.');return Math.max(start,now);}
export function planMtaJourney(request:RouteRequest,feeds:MtaFeed[],now=Date.now()):RoutePlan{
 const start=validateMtaRequest(request,now);if(!feeds.some(f=>fresh(f,now)))throw new MtaError('No fresh MTA predictions are available. Try again shortly.',503);
 const trips=predictions(feeds,now).filter(t=>!request.blockedLines?.includes(t.line));
 const journeys:{journey:Journey;timestamps:string[]}[]=[];
 function visit(at:string,time:number,legs:Leg[],seen:Set<string>,lastStop?:string,timestamps:string[]=[],walkingSeconds=0){if(legs.length>=3||journeys.length>=1000)return;for(const trip of trips){if(legs.some(l=>l.continuationId===trip.id))continue;for(let i=0;i<trip.stops.length;i++){const from=trip.stops[i];if(from.station!==at)continue;const transfer=lastStop?transferSeconds(lastStop,from.stopId):0;if((walkingSeconds+transfer)/60>(request.maxWalkMinutes??20))continue;if(from.departure<time+transfer*1000)continue;for(const to of trip.stops.slice(i+1)){if(seen.has(to.station)||to.arrival<from.departure)continue;const leg:Leg={from:at,to:to.station,fromName:station(at).name,toName:station(to.station).name,line:trip.line,direction:direction(from.stopId),departureTime:iso(from.departure),arrivalTime:iso(to.arrival),walk:false,minutes:(to.arrival-from.departure)/60000,continuationId:trip.id};const next=[...legs,leg],times=[...timestamps,trip.sourceTimestamp];if(to.station===request.destination){journeys.push({journey:{legs:next,departureTime:iso(start),arrivalTime:iso(to.arrival),arrivalRange:[iso(to.arrival),iso(to.arrival)],durationMinutes:(to.arrival-start)/60000,transfers:next.length-1,nextInstruction:`Take ${next[0].line} ${next[0].direction} from ${next[0].fromName} to ${next[0].toName}. Verify the train destination before boarding.`},timestamps:times});}else visit(to.station,to.arrival,next,new Set([...seen,to.station]),to.stopId,times,walkingSeconds+transfer);}}}}
 visit(request.origin,start,[],new Set([request.origin]));journeys.sort((a,b)=>(a.journey.durationMinutes+a.journey.transfers*(request.preferFewerTransfers?12:2))-(b.journey.durationMinutes+b.journey.transfers*(request.preferFewerTransfers?12:2)));if(!journeys.length)throw new MtaError('No predicted connection is currently available between these supported stations. Try another station or refresh.');const selected=journeys[0];return {recommended:selected.journey,alternative:journeys[1]?.journey??null,freshness:{mode:'live',sourceTimestamp:[...selected.timestamps,...(journeys[1]?.timestamps??[])].sort()[0],stale:false},warnings:[...warnings,'Arrival time is a point prediction; no confidence interval is supplied.',...(feeds.some(f=>!fresh(f,now))?['Some feeds are unavailable; route choices may be incomplete.']:[])]};
}
