import {test} from 'node:test';import assert from 'node:assert/strict';
import {RewardsPayoutService,type PayoutAdapter} from '../src/payout.js';
function fixture(){const state:any={ledger:{l:{id:'l',accountId:'a',groupId:'g',amount:600000,status:'payable'}},wallets:{a:{accountId:'a',address:'wallet'}},payouts:{},feeSpentLamports:0,feeReservedLamports:0};let tail=Promise.resolve();const repo:any={transact:(fn:any)=>{const next=tail.then(async()=>{const draft=structuredClone(state);const out=await fn(draft);Object.assign(state,draft);return structuredClone(out)});tail=next.catch(()=>{});return next}};let prepares=0,sends=0;let status:any='unknown';const adapter:PayoutAdapter={prepare:async()=>{prepares++;return {signature:'signature',raw:'bytes',lastValidBlockHeight:100,feeLamports:5000,setupLamports:0,destination:'ata',createsAta:false}},broadcast:async()=>{sends++;throw Error('RPC timeout after send')},status:async()=>status};return {state,repo,adapter,counts:()=>({prepares,sends}),setStatus:(v:any)=>status=v}}
test('concurrent claims and crash retries reserve once and never resign ambiguous transaction',async()=>{const f=fixture();const s=new RewardsPayoutService(f.repo,f.adapter);const [a,b]=await Promise.all([s.claim('a','g'),s.claim('a','g')]);assert.equal(a.id,b.id);await s.process(a.id);assert.equal(f.state.payouts[a.id].status,'unknown');await new RewardsPayoutService(f.repo,f.adapter).process(a.id);assert.equal(f.counts().prepares,1);assert.equal(f.state.ledger.l.status,'reserved');f.setStatus('finalized');await s.process(a.id);assert.equal(f.state.ledger.l.status,'settled');await assert.rejects(()=>s.claim('a','g'),/threshold/)});
test('failed finalized transaction restores liability but accounts conservatively for SOL fee',async()=>{const f=fixture();const s=new RewardsPayoutService(f.repo,f.adapter);const p=await s.claim('a','g');await s.process(p.id);f.setStatus('failed');await s.process(p.id);assert.equal(f.state.ledger.l.status,'payable');assert.equal(f.state.feeReservedLamports,0);assert.ok(f.state.feeSpentLamports>0)});
test('fee exhaustion prevents signing and duplicate group cannot withdraw another account credit',async()=>{const f=fixture();const s=new RewardsPayoutService(f.repo,f.adapter,{feeBudgetLamports:1});await assert.rejects(()=>s.claim('a','g'),/fee budget/);assert.equal(f.state.ledger.l.status,'payable');await assert.rejects(()=>s.claim('a','other'),/threshold/)});
test('signed bytes commit before any send; lost signing commit never broadcasts',async()=>{const f=fixture();const s=new RewardsPayoutService(f.repo,f.adapter);const p=await s.claim('a','g');f.adapter.broadcast=async tx=>{assert.equal(f.state.payouts[p.id].signed.raw,tx.raw);assert.equal(f.state.payouts[p.id].signed.signature,tx.signature)};await s.process(p.id);assert.equal(f.state.payouts[p.id].status,'submitted');const g=fixture();const base=g.repo.transact;let failCommit=false;g.repo.transact=async(fn:any)=>base(async(state:any)=>{const result=await fn(state);if(failCommit)throw Error('simulated failed commit');return result});const service=new RewardsPayoutService(g.repo,g.adapter);const next=await service.claim('a','g');failCommit=true;await assert.rejects(()=>service.process(next.id),/failed commit/);assert.equal(g.counts().sends,0);assert.equal(g.state.payouts[next.id].status,'created')});
test('unsigned failed preparation can be cancelled once without consuming SOL or reward liabilities',async()=>{const f=fixture();f.adapter.prepare=async()=>{throw Error('Insufficient backend SOL')};const s=new RewardsPayoutService(f.repo,f.adapter);const p=await s.claim('a','g');await assert.rejects(()=>s.process(p.id),/Insufficient/);await assert.rejects(()=>s.cancelUnsigned(p.id,'other'),/Unknown payout/);const result=await s.cancelUnsigned(p.id,'a');assert.equal(result.status,'failed');assert.match(result.error!,/cancelled/);assert.equal(f.state.ledger.l.status,'payable');assert.equal(f.state.ledger.l.payoutId,undefined);assert.equal(f.state.feeReservedLamports,0);assert.equal(f.state.feeSpentLamports,0);await assert.rejects(()=>s.cancelUnsigned(p.id,'a'),/unsigned/);assert.equal(f.state.feeReservedLamports,0);assert.notEqual((await s.claim('a','g')).id,p.id)});
test('concurrent process and cancellation serialize; signed ambiguity can never release funds',async()=>{const f=fixture();const s=new RewardsPayoutService(f.repo,f.adapter);const p=await s.claim('a','g');const processed=s.process(p.id);await assert.rejects(()=>s.cancelUnsigned(p.id,'a'),/unsigned/);await processed;assert.equal(f.state.ledger.l.status,'reserved');await assert.rejects(()=>s.cancelUnsigned(p.id,'a'),/unsigned/);assert.equal(f.counts().prepares,1);const g=fixture();const service=new RewardsPayoutService(g.repo,g.adapter);const next=await service.claim('a','g');await Promise.all([service.cancelUnsigned(next.id,'a'),service.process(next.id)]);assert.equal(g.counts().prepares,0);assert.equal(g.counts().sends,0);assert.equal(g.state.ledger.l.status,'payable')});
test('changed amount or wallet rejects stale confirmation without reserving credit or fees',async()=>{
 for(const change of ['amount','wallet'] as const){
  const f=fixture();const service=new RewardsPayoutService(f.repo,f.adapter);
  const confirmation={expectedAmount:600000,expectedWallet:'wallet'};
  // Another session or moderator changes authoritative state after the confirmation is displayed.
  await f.repo.transact(async(state:any)=>{if(change==='amount')state.ledger.l.amount+=200000;else state.wallets.a.address='new-wallet'});
  const before=structuredClone(f.state);
  await assert.rejects(()=>service.claim('a','g',confirmation),/amount or wallet changed/);
  assert.deepEqual(f.state,before);assert.equal(Object.keys(f.state.payouts).length,0);
  assert.equal(f.state.ledger.l.status,'payable');assert.equal(f.state.feeReservedLamports,0);
  assert.deepEqual(f.counts(),{prepares:0,sends:0});
 }
});
test('matching confirmation reserves once and cannot resume a different pending payout',async()=>{
 const f=fixture();const service=new RewardsPayoutService(f.repo,f.adapter);
 const confirmation={expectedAmount:600000,expectedWallet:'wallet'};
 const [first,retry]=await Promise.all([service.claim('a','g',confirmation),service.claim('a','g',confirmation)]);
 assert.equal(first.id,retry.id);assert.equal(first.amount,confirmation.expectedAmount);assert.equal(first.recipient,confirmation.expectedWallet);
 const before=structuredClone(f.state);
 await assert.rejects(()=>service.claim('a','g',{...confirmation,expectedAmount:800000}),/amount or wallet changed/);
 await assert.rejects(()=>service.claim('a','g',{...confirmation,expectedWallet:'new-wallet'}),/amount or wallet changed/);
 assert.deepEqual(f.state,before);assert.equal(Object.keys(f.state.payouts).length,1);
 assert.equal((await service.claim('a','g')).id,first.id);
});
