import {z} from 'zod';
import {getRewardsService} from '../../../../../packages/rewards/src/runtime.ts';
import {guidanceForTrip} from '../../../../gateway/src/rewards.ts';
import {buildMtaBoard,collectMtaFeeds,feedStatuses,mtaStations,MtaError,planMtaJourney,validateMtaRequest} from '../../../../../packages/core/src/mta.ts';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'no-store'};
const schema=z.object({origin:z.string(),destination:z.string(),departureTime:z.string(),requireAccessible:z.boolean().optional(),preferFewerTransfers:z.boolean().optional(),maxWalkMinutes:z.number().min(0).max(120).optional(),blockedLines:z.array(z.string().max(8)).max(30).optional()}).strict();
export async function GET(request:Request){const station=new URL(request.url).searchParams.get('station')??'columbia';if(!mtaStations.some(s=>s.id===station))return Response.json({error:'Unknown station. Choose a supported MTA station.'},{status:400,headers});const feeds=await collectMtaFeeds();return Response.json(buildMtaBoard(station,feeds),{headers});}
export async function POST(request:Request){let parsed;try{const body=await request.text();if(body.length>10000)return Response.json({error:'Request too large.'},{status:413,headers});parsed=schema.safeParse(JSON.parse(body));}catch{return Response.json({error:'Invalid JSON request.'},{status:400,headers});}if(!parsed.success)return Response.json({error:'Invalid trip request.'},{status:400,headers});try{validateMtaRequest(parsed.data);}catch(error){return Response.json({error:error instanceof Error?error.message:'Invalid trip request.'},{status:error instanceof MtaError?error.status:400,headers});}const feeds=await collectMtaFeeds();try{const plan=planMtaJourney(parsed.data,feeds);if(process.env.MONGODB_URI){try{const rewards=await getRewardsService();const guidance=guidanceForTrip(await rewards.liveObservations(),plan);plan.warnings.push(...guidance.map(g=>g.message));}catch{/* Optional observations never replace official MTA routing or block navigation. */}}return Response.json({plan,feeds:feedStatuses(feeds),warnings:plan.warnings},{headers});}catch(error){return Response.json({error:error instanceof Error?error.message:'MTA routing unavailable.',feeds:feedStatuses(feeds)},{status:error instanceof MtaError?error.status:503,headers});}}
