import {randomUUID} from 'node:crypto';
import {payoutReceipt} from './payout.ts';
import type {RewardsRepository,RewardState} from './repository.ts';
export type Category='platform_crowding'|'boarding_difficulty'|'elevator_status'|'escalator_status'|'entrance_obstruction';
export interface Identity {accountId:string;groupId:string}
export interface ObservationTarget {station:string;category:Category;asset?:string;direction?:string;platform?:string}
export interface ReportInput extends ObservationTarget {condition:string;observedAt:number;evidenceRefs?:string[];taskId?:string}
export type ReportStatus='received'|'pending'|'corroborated'|'verified'|'disputed'|'expired'|'rejected'|'reward_eligible';
export interface AuditEntry {at:number;action:string;reason:string;actor?:string}
export interface EvidenceReview extends ObservationTarget {kind:'official'|'moderator';reviewerId:string;reference:string;condition:string;observedAt:number;decision:'accept'|'reject';reason:string;knownAt?:number;independentSupportReference?:string}
export interface ObservationReport extends ReportInput,Identity {id:string;submissionId?:string;targetKey:string;receivedAt:number;status:ReportStatus;verificationStatus:'pending'|'corroborated'|'verified'|'rejected'|'disputed'|'expired';rewardStatus:'pending'|'reward_eligible'|'unpaid';provisionalAmount:number;slot?:number;taskId?:string;reviews:EvidenceReview[];audit:AuditEntry[];corroboratingGroups:string[];flags:string[];affectedTripIds?:string[];guidanceChanged?:boolean}
export interface RewardSlot {index:number;weight:number;amount:number;accountId?:string;groupId?:string;reportId?:string;status:'open'|'assigned'|'earned'|'invalid'|'expired'}
export interface BountyCalculation {formulaVersion:string;coverage:number;target:number;baseReward:number;gapNumerator:number;gapDenominator:number;bounty:number;slots:number[]}
export interface ObservationTask {id:string;target:ObservationTarget;targetAliases?:ObservationTarget[];targetKey:string;windowStart:number;openedAt:number;expiresAt:number;day:string;funded:boolean;reason:string;requestedRefresh?:boolean;calculation:BountyCalculation;slots:RewardSlot[];reservation:number;status:'active'|'closed'|'expired';audit:AuditEntry[]}
export interface RewardCredit {id:string;reportId:string;taskId:string;groupId:string;accountId:string;amount:number;status:'payable'|'reserved'|'settled';payoutId?:string;createdAt:number}
export interface RewardsConfig {allocatedFunding:number;dailyBudget:number;groupDailyCap:number;maxActiveDiscoveries:number;stationLimit:number;categoryLimit:number;baseReward:number;targetCoverage:number;coverageWindowMs:number;taskTtlMs:number;freshnessMs:Partial<Record<Category,number>>;cooldownMs:Partial<Record<Category,number>>}
const freshness:Record<Category,number>={platform_crowding:10*60_000,boarding_difficulty:10*60_000,elevator_status:30*60_000,escalator_status:30*60_000,entrance_obstruction:20*60_000};
const categories=Object.keys(freshness);
const clean=(s:string)=>s.trim().replace(/\s+/g,' ').toLowerCase();
const direction=(value:string)=>({downtown:'southbound',uptown:'northbound',south:'southbound',north:'northbound',east:'eastbound',west:'westbound'}[clean(value)]??clean(value));
const day=(at:number)=>new Date(at).toISOString().slice(0,10);
export function canonicalTarget(t:ObservationTarget):string{const equipment=['elevator_status','escalator_status','entrance_obstruction'].includes(t.category);return JSON.stringify([clean(t.station),t.category,equipment?clean(t.asset??''):t.direction?.trim()?`direction:${direction(t.direction)}`:`platform:${clean(t.platform??'')}`])}
function sameTarget(a:ObservationTarget,b:ObservationTarget):boolean{if(canonicalTarget(a)===canonicalTarget(b))return true;return ['platform_crowding','boarding_difficulty'].includes(a.category)&&a.category===b.category&&clean(a.station)===clean(b.station)&&!!a.platform?.trim()&&!!b.platform?.trim()&&clean(a.platform)===clean(b.platform)}
function taskMatches(task:ObservationTask,target:ObservationTarget):boolean{return [task.target,...(task.targetAliases??[])].some(alias=>sameTarget(alias,target))}
function learnAlias(task:ObservationTask,input:ObservationTarget){if(!['platform_crowding','boarding_difficulty'].includes(input.category)||!input.platform?.trim()||!input.direction?.trim())return;const alias={station:input.station,category:input.category,platform:clean(input.platform),direction:direction(input.direction)};task.targetAliases??=[];if(!task.targetAliases.some(a=>a.platform===alias.platform&&a.direction===alias.direction))task.targetAliases.push(alias)}
export function calculateBounty(coverage:number,target=3,baseReward=500_000):BountyCalculation {for(const n of [coverage,target,baseReward])if(!Number.isSafeInteger(n)||n<0)throw Error('Invalid bounty input');if(!target)throw Error('Coverage target must be positive');const missing=Math.max(target-coverage,0);const bounty=baseReward+Number(BigInt(baseReward)*BigInt(missing)/BigInt(target));if(!Number.isSafeInteger(bounty))throw Error('Bounty overflow');return {formulaVersion:'coverage-v1',coverage,target,baseReward,gapNumerator:missing,gapDenominator:target,bounty,slots:[Number(BigInt(bounty)*60n/100n),Number(BigInt(bounty)*20n/100n),Number(BigInt(bounty)*20n/100n)]}}
export class RewardsService {
 readonly config:RewardsConfig;
 constructor(readonly repo:RewardsRepository,config:Partial<RewardsConfig>={},private clock=()=>Date.now()){
 this.config={allocatedFunding:0,dailyBudget:config.allocatedFunding??0,groupDailyCap:2_000_000,maxActiveDiscoveries:2,stationLimit:config.allocatedFunding??0,categoryLimit:config.allocatedFunding??0,baseReward:500_000,targetCoverage:3,coverageWindowMs:60*60_000,taskTtlMs:30*60_000,freshnessMs:{},cooldownMs:{},...config};
 for(const [k,v] of Object.entries(this.config))if(typeof v==='number'&&(!Number.isSafeInteger(v)||v<0))throw Error(`Invalid ${k}`);for(const values of [this.config.freshnessMs,this.config.cooldownMs])for(const value of Object.values(values))if(!Number.isSafeInteger(value)||value!<=0)throw Error('Invalid category timing');if(!this.config.targetCoverage||!this.config.taskTtlMs)throw Error('Positive target and expiry required');
 }
 private transaction<T>(fn:(state:RewardState)=>Promise<T>):Promise<T>{return this.repo.transact(async s=>{const stable=(value:unknown):string=>JSON.stringify(value,(_key,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);if(s.campaignConfig&&stable(s.campaignConfig)!==stable(this.config)){const firstFunding=s.campaignConfig.allocatedFunding===0&&this.config.allocatedFunding>0&&Object.keys(s.ledger).length===0&&Object.keys(s.payouts).length===0&&Object.values(s.tasks).every(t=>t.reservation===0);if(!firstFunding)throw Error('Campaign funding policy differs from persisted allocation; explicit campaign migration required');s.campaignConfig=structuredClone(this.config);for(const t of Object.values(s.tasks))if(!t.funded&&t.status==='active'){t.status='expired';t.audit.push({at:this.clock(),action:'campaign_funded',reason:'Previously unpaid task may now receive a funded replacement'})}}s.campaignConfig??=structuredClone(this.config);return fn(s)})}
 private age(category:Category){return this.config.freshnessMs[category]??freshness[category]}
 private validate(input:ReportInput,identity:Identity){if(!identity.accountId||!identity.groupId)throw Error('Authenticated reward identity required');if(!input.station?.trim()||!categories.includes(input.category)||!input.condition?.trim())throw Error('Station, category and condition required');if(['elevator_status','escalator_status','entrance_obstruction'].includes(input.category)&&!input.asset?.trim())throw Error('Specific equipment or entrance required');if(['platform_crowding','boarding_difficulty'].includes(input.category)&&!input.direction?.trim()&&!input.platform?.trim())throw Error('Direction or platform required');if(!Number.isFinite(input.observedAt)||input.observedAt>this.clock()+120_000)throw Error('Invalid observation time');if([input.station,input.asset,input.platform,input.direction,input.condition].some(v=>v&&v.length>200))throw Error('Observation field too long')}
 private expire(s:RewardState,now:number){for(const task of Object.values(s.tasks))if(task.status==='active'&&task.expiresAt<=now){task.status='expired';task.reservation=0;for(const slot of task.slots)if(slot.status==='open'||slot.status==='assigned')slot.status='expired';task.audit.push({at:now,action:'expired',reason:'Unused reservations released; earned rewards retained'})}for(const r of Object.values(s.reports))if(['pending','corroborated'].includes(r.verificationStatus)&&now-r.receivedAt>this.config.taskTtlMs){r.verificationStatus='expired';r.status='expired';r.rewardStatus='unpaid';r.audit.push({at:now,action:'expired',reason:'Insufficient evidence before reward expiry; no abuse determination'})}}
 private accounting(s:RewardState){const credits=Object.values(s.ledger);const activeReservations=Object.values(s.tasks).reduce((n,t)=>n+t.reservation,0);const committedUnpaid=credits.filter(c=>c.status!=='settled').reduce((n,c)=>n+c.amount,0);const settled=credits.filter(c=>c.status==='settled').reduce((n,c)=>n+c.amount,0);return {allocatedFunding:this.config.allocatedFunding,activeReservations,committedUnpaid,settled,totalCommitted:activeReservations+committedUnpaid+settled}}
 private exposure(s:RewardState,groupId:string,at:number){return Object.values(s.ledger).filter(c=>c.groupId===groupId&&day(c.createdAt)===day(at)).reduce((n,c)=>n+c.amount,0)+Object.values(s.tasks).filter(t=>t.day===day(at)&&t.status==='active').flatMap(t=>t.slots).filter(sl=>sl.groupId===groupId&&sl.status==='assigned').reduce((n,sl)=>n+sl.amount,0)}
 private takeSlot(s:RewardState,t:ObservationTask,index:number,identity:Identity,now:number){const existing=t.slots.find(sl=>sl.groupId===identity.groupId);if(existing){if(existing.accountId!==identity.accountId)throw Error('Known linked account already occupies a slot');return existing}const slot=t.slots[index];if(!t.funded||t.status!=='active'||slot.status!=='open')throw Error('No funded slot available');if(this.exposure(s,identity.groupId,now)+slot.amount>this.config.groupDailyCap)throw Error('Contributor daily cap reached');if(index===0&&Object.values(s.tasks).filter(x=>x.status==='active'&&x.slots[0].groupId===identity.groupId&&x.slots[0].status==='assigned').length>=this.config.maxActiveDiscoveries)throw Error('Active discovery cap reached');Object.assign(slot,identity,{status:'assigned'});return slot}
 private open(s:RewardState,input:ReportInput,now:number,authorization?:string){const key=canonicalTarget(input);const all=Object.values(s.tasks).filter(t=>taskMatches(t,input)).sort((a,b)=>b.openedAt-a.openedAt);const active=all.find(t=>t.status==='active');if(active){learnAlias(active,input);return active;}const previous=all.find(t=>t.funded);const cooldown=this.config.cooldownMs[input.category]??this.age(input.category);if(previous&&(!authorization||now-previous.openedAt<cooldown))return undefined;
 const matching=Object.values(s.reports).filter(r=>r.verificationStatus==='verified'&&clean(r.station)===clean(input.station)&&r.category===input.category&&r.observedAt>=now-this.config.coverageWindowMs&&r.observedAt<=now);const calculation=calculateBounty(new Set(matching.map(r=>r.groupId)).size,this.config.targetCoverage,this.config.baseReward);const known=s.knownConditions?.[key];const alreadyKnown=known&&clean(known.condition)===clean(input.condition)&&now-known.observedAt<this.age(input.category);if(alreadyKnown&&!authorization)return undefined;const live=Object.values(s.reports).some(r=>r.targetKey===key&&r.verificationStatus==='verified'&&now-r.observedAt<this.age(r.category));if(live&&!authorization)return undefined;
 const total=this.accounting(s).totalCommitted;const allocated=(pred:(t:ObservationTask)=>boolean)=>Object.values(s.tasks).filter(pred).reduce((n,t)=>n+t.reservation+Object.values(s.ledger).filter(c=>c.taskId===t.id).reduce((a,c)=>a+c.amount,0),0);
 let reason=authorization??'Unknown or stale transit condition';let funded=now-input.observedAt<=this.age(input.category);if(!funded)reason='Observation too old for reward';if(total+calculation.bounty>this.config.allocatedFunding||allocated(t=>t.day===day(now))+calculation.bounty>this.config.dailyBudget||allocated(t=>clean(t.target.station)===clean(input.station))+calculation.bounty>this.config.stationLimit||allocated(t=>t.target.category===input.category)+calculation.bounty>this.config.categoryLimit){funded=false;reason='Campaign allocation exhausted; useful reports accepted unpaid'}
 const target={station:input.station,category:input.category,asset:input.asset,direction:input.direction,platform:input.platform};const t:ObservationTask={id:randomUUID(),target,targetKey:key,windowStart:Math.floor(now/this.config.taskTtlMs)*this.config.taskTtlMs,openedAt:now,expiresAt:Math.min(now+this.config.taskTtlMs,Date.parse(day(now))+86_400_000),day:day(now),funded,reason,requestedRefresh:!!authorization,calculation,slots:calculation.slots.map((amount,index)=>({index,amount,weight:[60,20,20][index],status:'open'})),reservation:funded?calculation.bounty:0,status:'active',audit:[{at:now,action:'opened',reason}]};s.tasks[t.id]=t;return t;
 }
 private prepare(s:RewardState,input:ReportInput,identity:Identity,now:number){const existingIds=new Set(Object.keys(s.tasks));let t=input.taskId?s.tasks[input.taskId]:this.open(s,input,now);if(t&&!taskMatches(t,input))throw Error('Assignment target mismatch');if(t)learnAlias(t,input);let slot:RewardSlot|undefined;let reason=t?.reason??'Known condition or refresh requires server authorization';if(t?.status==='active'&&t.funded){const own=t.slots.find(sl=>sl.groupId===identity.groupId&&sl.accountId===identity.accountId);if(own&&!own.reportId&&own.status==='assigned')slot=own;else if(!own){try{slot=this.takeSlot(s,t,0,identity,now)}catch(error){reason=(error as Error).message;if(!existingIds.has(t.id)){delete s.tasks[t.id];t=undefined}}}else reason='Duplicate contribution receives no extra reward'}return {taskId:t?.id,funded:!!slot,provisionalAmount:slot?.amount??0,reason:slot?'Reserved provisional reward; verification required':reason,expiresAt:t?.expiresAt,calculation:t?.calculation}}
 async prepareReport(input:ReportInput,identity:Identity){this.validate(input,identity);return this.transaction(async s=>{const now=this.clock();this.expire(s,now);return this.prepare(s,input,identity,now)})}
 async preview(input:ReportInput,identity:Identity){return this.prepareReport(input,identity)}
 async submitReport(input:ReportInput,identity:Identity,options:{requireFunded?:boolean;requireProvisionalAmount?:number;submissionId?:string}={}){this.validate(input,identity);return this.transaction(async s=>{if(options.submissionId){const prior=Object.values(s.reports).find(r=>r.accountId===identity.accountId&&r.submissionId===options.submissionId);if(prior)return {report:prior,task:prior.taskId?s.tasks[prior.taskId]:undefined,provisionalAmount:prior.provisionalAmount,reason:'Report already received'};}const now=this.clock();this.expire(s,now);const quote=this.prepare(s,input,identity,now);const task=quote.taskId?s.tasks[quote.taskId]:undefined;const slot=task?.slots.find(sl=>sl.groupId===identity.groupId&&sl.accountId===identity.accountId&&sl.status==='assigned'&&!sl.reportId);if(options.requireFunded&&!slot)throw Error('Reserved reward expired or unavailable; request a new quote before submission');if(options.requireProvisionalAmount!==undefined&&(slot?.amount??0)!==options.requireProvisionalAmount)throw Error('Reserved amount changed; request a new quote');const refs=input.evidenceRefs??[];const repeated=refs.length>0&&Object.values(s.reports).some(r=>r.groupId!==identity.groupId&&r.evidenceRefs?.some(ref=>refs.includes(ref)));const id=randomUUID();const stale=now-input.observedAt>this.age(input.category);const report:ObservationReport={...input,...identity,id,submissionId:options.submissionId,targetKey:canonicalTarget(input),receivedAt:now,taskId:task?.id,slot:slot?.index,provisionalAmount:slot?.amount??0,status:stale?'expired':'pending',verificationStatus:stale?'expired':'pending',rewardStatus:slot&&!stale?'pending':'unpaid',reviews:[],audit:[{at:now,action:'received',reason:quote.reason},{at:now,action:stale?'expired':'pending',reason:stale?'Observation outside category freshness window':'Awaiting concrete official or moderator evidence'}],corroboratingGroups:[],flags:repeated?['repeated_evidence']:[]};if(slot){slot.reportId=id;if(stale){slot.status='invalid';task!.reservation-=slot.amount;report.provisionalAmount=0}}s.reports[id]=report;return {report,task,provisionalAmount:report.provisionalAmount,reason:quote.reason}})}
 async assignCheck(taskId:string,identity:Identity){return this.transaction(async s=>{const now=this.clock();this.expire(s,now);const t=s.tasks[taskId];if(!t)throw Error('Unknown task');if(t.slots.some(sl=>sl.groupId===identity.groupId))throw Error('One slot per contributor group');const index=t.slots.findIndex(sl=>sl.index>0&&sl.status==='open');if(index<0)throw Error('No independent check slots');const slot=this.takeSlot(s,t,index,identity,now);const discoverer=t.slots[0].groupId;const reciprocal=discoverer&&Object.values(s.tasks).some(other=>other.slots[0].groupId===identity.groupId&&other.slots.some(sl=>sl.index>0&&sl.groupId===discoverer));if(reciprocal)t.audit.push({at:now,action:'reciprocal_check_flag',reason:'Repeated groups checking one another; moderator review requires independent evidence'});return {taskId:t.id,target:t.target,slot:slot.index,amount:slot.amount,expiresAt:t.expiresAt,prompt:'What is the current condition? Report your own observation without consulting other reports.'}})}
 async assignCheckAt(station:string,identity:Identity){const candidates=await this.transaction(async s=>{this.expire(s,this.clock());return Object.values(s.tasks).filter(t=>clean(t.target.station)===clean(station)&&t.funded&&t.status==='active'&&!t.slots.some(sl=>sl.groupId===identity.groupId)&&t.slots.some(sl=>sl.index>0&&sl.status==='open')).map(t=>t.id)});for(const id of candidates){try{return await this.assignCheck(id,identity)}catch{/* Another caller may have taken this slot; try another bounded candidate. */}}throw Error('No eligible independent checks at this station')}
 async recordGuidance(reportId:string,tripId:string){return this.transaction(async s=>{const r=s.reports[reportId];if(!r||r.verificationStatus!=='verified'||this.clock()-r.observedAt>this.age(r.category))return false;r.affectedTripIds=[...new Set([...(r.affectedTripIds??[]),tripId])];r.guidanceChanged=true;return true})}
 async recordKnownCondition(evidence:EvidenceReview){if(evidence.kind!=='official'||!evidence.reference||!Number.isFinite(evidence.observedAt)||evidence.observedAt>this.clock()+120_000)throw Error('Trusted official condition required');return this.transaction(async s=>{s.knownConditions??={};s.knownConditions[canonicalTarget(evidence)]={condition:evidence.condition,observedAt:evidence.observedAt,knownAt:this.clock(),reference:evidence.reference}})}
 async authorizeRefresh(input:ReportInput,authorization:{reviewerId:string;reason:string;reference:string}){if(!authorization.reviewerId||!authorization.reason||!authorization.reference)throw Error('Recorded server review required');return this.transaction(async s=>{this.expire(s,this.clock());return this.open(s,input,this.clock(),`${authorization.reason} (${authorization.reference}; ${authorization.reviewerId})`)})}
 async corroborate(reportId:string,identity:Identity){return this.transaction(async s=>{const r=s.reports[reportId];if(!r)throw Error('Unknown report');if(r.groupId===identity.groupId)throw Error('Independent contributor required');if(!r.corroboratingGroups.includes(identity.groupId))r.corroboratingGroups.push(identity.groupId);if(r.verificationStatus==='pending'){r.verificationStatus='corroborated';r.status='corroborated'}if(r.corroboratingGroups.length>=3)r.flags=[...new Set([...r.flags,'coordinated_burst_review'])];r.audit.push({at:this.clock(),action:'corroborated',actor:identity.accountId,reason:'Peer report prioritizes review; it cannot authorize rewards'});return r})}
 async review(reportId:string,evidence:EvidenceReview){return this.transaction(async s=>{const now=this.clock();this.expire(s,now);const r=s.reports[reportId];if(!r)throw Error('Unknown report');if(!['accept','reject'].includes(evidence.decision))throw Error('Invalid review decision');if(!['official','moderator'].includes(evidence.kind)||!evidence.reviewerId||!evidence.reference?.trim()||!evidence.reason?.trim())throw Error('Concrete evidence and authenticated reviewer required');if(canonicalTarget(evidence)!==r.targetKey||!Number.isFinite(evidence.observedAt)||Math.abs(evidence.observedAt-r.observedAt)>this.age(r.category)||evidence.observedAt>now+120_000)throw Error('Evidence target or time mismatch');if(evidence.decision==='accept'&&clean(evidence.condition)!==clean(r.condition))throw Error('Evidence condition mismatch');r.reviews.push(evidence);r.audit.push({at:now,action:evidence.decision,actor:evidence.reviewerId,reason:evidence.reason});const t=r.taskId?s.tasks[r.taskId]:undefined;const slot=t?.slots.find(sl=>sl.reportId===r.id);if(evidence.decision==='reject'){r.status='rejected';r.verificationStatus='rejected';if(r.rewardStatus!=='reward_eligible')r.rewardStatus='unpaid';else r.audit.push({at:now,action:'earned_reward_preserved',reason:'Historical earned liability retained while mistaken guidance is withdrawn'});if(slot?.status==='assigned'){slot.status='invalid';t!.reservation-=slot.amount}return r}
 r.verificationStatus='verified';r.status=r.rewardStatus==='reward_eligible'?'reward_eligible':'verified';if(evidence.kind==='moderator'&&evidence.independentSupportReference?.trim()&&!(r.evidenceRefs??[]).includes(evidence.independentSupportReference)&&evidence.independentSupportReference!==evidence.reference){r.flags=r.flags.filter(f=>f!=='repeated_evidence');r.audit.push({at:now,action:'independent_evidence_override',actor:evidence.reviewerId,reason:evidence.independentSupportReference})}const copied=evidence.kind==='official'&&evidence.knownAt!==undefined&&evidence.knownAt<=r.receivedAt&&r.slot===0&&!t?.requestedRefresh;const eligible=!!slot&&slot.status==='assigned'&&t!.status==='active'&&now<t!.expiresAt&&r.receivedAt-r.observedAt<=this.age(r.category)&&!copied&&!r.flags.includes('repeated_evidence');if(eligible){const id=randomUUID();s.ledger[id]={id,reportId:r.id,taskId:t!.id,groupId:r.groupId,accountId:r.accountId,amount:slot!.amount,status:'payable',createdAt:now};slot!.status='earned';t!.reservation-=slot!.amount;r.rewardStatus='reward_eligible';r.status='reward_eligible';r.audit.push({at:now,action:'reward_eligible',reason:`Fixed slot ${slot!.index}; ${slot!.amount} micro-USDC; ${t!.calculation.formulaVersion}`})}else if(r.rewardStatus!=='reward_eligible'){r.rewardStatus='unpaid';r.audit.push({at:now,action:'unpaid',reason:copied?'Already-known official evidence provides no novelty':r.flags.includes('repeated_evidence')?'Repeated evidence requires independent supporting evidence':'No active assigned reward slot'})}return r})}
 async dispute(reportId:string,identity:Identity,reason:string){if(!reason.trim())throw Error('Appeal reason required');return this.transaction(async s=>{const r=s.reports[reportId];if(!r)throw Error('Unknown report');if(r.groupId!==identity.groupId||r.accountId!==identity.accountId)throw Error('Only the report owner can appeal');r.status='disputed';r.verificationStatus='disputed';r.audit.push({at:this.clock(),action:'disputed',actor:identity.accountId,reason});return r})}
 async liveObservations(){return this.transaction(async s=>{const now=this.clock();return Object.values(s.reports).filter(r=>r.verificationStatus==='verified'&&now-r.observedAt<=this.age(r.category)&&r.observedAt<=now+120_000).map(r=>({id:r.id,station:r.station,category:r.category,asset:r.asset,direction:r.direction,platform:r.platform,condition:r.condition,observedAt:r.observedAt,expiresAt:r.observedAt+this.age(r.category),verification:r.reviews.at(-1)?.kind}))})}
 async snapshot(groupId?:string,accountId?:string){return this.transaction(async s=>{this.expire(s,this.clock());const ledger=Object.values(s.ledger).filter(c=>(!groupId||c.groupId===groupId)&&(!accountId||c.accountId===accountId));const reports=Object.values(s.reports).filter(r=>(!groupId||r.groupId===groupId)&&(!accountId||r.accountId===accountId));return {network:'devnet' as const,currency:'test USDC',tasks:Object.values(s.tasks).filter(t=>!groupId||t.slots.some(sl=>sl.groupId===groupId&&(!accountId||sl.accountId===accountId))||reports.some(r=>r.taskId===t.id)).map(t=>groupId?{...t,audit:[],slots:t.slots.map(sl=>sl.groupId===groupId&&(!accountId||sl.accountId===accountId)?sl:{index:sl.index,amount:sl.amount,weight:sl.weight,status:sl.status})}:t),reports:reports.map(r=>groupId?{...r,corroboratingGroups:[],affectedTripIds:[],reviews:r.reviews.map(e=>({...e,reviewerId:'reviewer'})),audit:r.audit.map(a=>({...a,actor:undefined}))}:r),ledger,payouts:Object.values(s.payouts).filter(p=>(!groupId||p.groupId===groupId)&&(!accountId||p.accountId===accountId)).map(p=>({...p,receipt:payoutReceipt(p),signed:undefined,recipient:undefined,error:undefined})),earnedBalance:ledger.reduce((n,c)=>n+c.amount,0),claimableBalance:ledger.filter(c=>c.status==='payable').reduce((n,c)=>n+c.amount,0),accounting:this.accounting(s),verificationReasons:reports.flatMap(r=>r.audit),samplingWarning:'Rewards influence who reports and where. Report frequency is not unbiased transit demand.'}})}
}
