import {createPublicKey,randomUUID,verify} from 'node:crypto';
import {PublicKey} from '@solana/web3.js';
import bs58 from 'bs58';
import type {RewardsRepository} from './repository.js';
export interface WalletBinding {accountId:string;address:string;boundAt:number}
export interface WalletNonce {id:string;accountId:string;address:string;domain:string;message:string;expiresAt:number;usedAt?:number}
/** Application authentication precedes every call; wallet possession never identifies an account. */
export class WalletService {
 constructor(private repo:RewardsRepository,private domain:string,private cooldownMs=86_400_000){const url=new URL(domain);if(url.origin!==domain)throw Error('Wallet domain must be an origin')}
 async challenge(accountId:string,address:string,now=Date.now()) {const key=new PublicKey(address);if(!PublicKey.isOnCurve(key.toBytes()))throw Error('Wallet must be an Ed25519 owner');return this.repo.transact(async state=>{const existing=state.wallets[accountId];if(existing&&existing.address!==address&&now-existing.boundAt<this.cooldownMs)throw Error('Wallet change cooldown active');const id=randomUUID(),expiresAt=now+300_000;const nonce:WalletNonce={id,accountId,address,domain:this.domain,expiresAt,message:`ExitNow Rider Rewards wallet binding\nDomain: ${this.domain}\nNetwork: solana:devnet\nAccount: ${accountId}\nWallet: ${address}\nNonce: ${id}\nExpires: ${new Date(expiresAt).toISOString()}\nThis signature links your payout wallet. It does not authorize a token transfer.`};state.nonces[id]=nonce;return nonce})}
 async bind(accountId:string,nonceId:string,signature:string,now=Date.now()){return this.repo.transact(async state=>{const nonce=state.nonces[nonceId];if(!nonce||nonce.accountId!==accountId||nonce.usedAt!==undefined||nonce.domain!==this.domain)throw Error('Invalid wallet nonce');if(now>nonce.expiresAt)throw Error('Wallet nonce expired');const previous=state.wallets[accountId];if(previous&&previous.address!==nonce.address&&now-previous.boundAt<this.cooldownMs)throw Error('Wallet change cooldown active');if(Object.values(state.payouts).some(p=>p.accountId===accountId&&!['finalized','failed'].includes(p.status)))throw Error('Resolve pending payout before changing wallet');if(Object.values(state.wallets).some(w=>w.accountId!==accountId&&w.address===nonce.address))throw Error('Wallet is already linked to another reward account');let valid=false;try{const key=createPublicKey({key:Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),Buffer.from(new PublicKey(nonce.address).toBytes())]),format:'der',type:'spki'});valid=verify(null,Buffer.from(nonce.message),key,bs58.decode(signature))}catch{}if(!valid)throw Error('Invalid wallet signature');nonce.usedAt=now;const binding={accountId,address:nonce.address,boundAt:previous?.address===nonce.address?previous.boundAt:now};state.wallets[accountId]=binding;return binding})}
}
