import {observationInput} from '../../../../gateway/src/rewards.ts';
import bs58 from 'bs58';
import {authenticateRider,moderatorAuthorized,resolveRewardIdentity} from '../../../../../packages/rewards/src/auth.ts';
import {getRewardsContext,getWalletService,getPayoutService,payoutThreshold} from '../../../../../packages/rewards/src/runtime.ts';
import {payoutReceipt} from '../../../../../packages/rewards/src/payout.ts';
import {boundedBody} from '../../../../../packages/planning/src/operator.ts';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'private, no-store'};
function auth(request:Request){const review=new URL(request.url).searchParams.get('review')==='1';if(review)return moderatorAuthorized(request)?{review:true,identity:null}:null;const session=authenticateRider(request);return session?{review:false,identity:resolveRewardIdentity(session.accountId)}:null}
export async function GET(request:Request){const access=auth(request);if(!access)return Response.json({error:'Access expired or invalid. Request a new private code from Grok Bot.'},{status:401,headers});try{const {service,repo}=await getRewardsContext();const data=await service.snapshot(access.identity?.groupId,access.identity?.accountId);const accountId=access.identity?.accountId;const reports=data.reports.filter(r=>!accountId||r.accountId===accountId);const ledger=data.ledger.filter(l=>!accountId||l.accountId===accountId);const wallet=accountId?await repo.transact(async s=>s.wallets[accountId]?.address):undefined;return Response.json({reports:reports.map(r=>({id:r.id,station:r.station,category:r.category,condition:r.condition,status:r.status,observedAt:r.observedAt,reason:r.audit.at(-1)?.reason??'Awaiting evidence',amount:r.provisionalAmount,earnedAmount:ledger.filter(c=>c.reportId===r.id).reduce((n,c)=>n+c.amount,0),verificationStatus:r.verificationStatus,rewardStatus:r.rewardStatus,receivedAt:r.receivedAt,calculation:data.tasks.find(t=>t.id===r.taskId)?.calculation,slot:r.slot,expiresAt:data.tasks.find(t=>t.id===r.taskId)?.expiresAt,taskId:r.taskId,asset:r.asset,platform:r.platform,direction:r.direction,evidenceRefs:access.review?r.evidenceRefs:undefined,reviews:access.review?r.reviews:undefined})),earnedBalance:ledger.reduce((n,c)=>n+c.amount,0),claimableBalance:ledger.filter(c=>c.status==='payable').reduce((n,c)=>n+c.amount,0),payouts:data.payouts.filter(p=>!accountId||p.accountId===accountId).map(p=>({id:p.id,amount:p.amount,status:p.status,receipt:p.receipt})),wallet,threshold:payoutThreshold(),samplingWarning:data.samplingWarning,...(access.review?{accounting:data.accounting,metrics:{usableObservations:data.reports.filter(r=>r.verificationStatus==='verified').length,guidanceChanges:data.reports.filter(r=>r.guidanceChanged).length,rewardSpend:data.ledger.reduce((n,c)=>n+c.amount,0)},tasks:data.tasks.map(t=>({id:t.id,station:t.target.station,category:t.target.category,bounty:t.calculation.bounty,coverageCount:t.calculation.coverage,expiresAt:t.expiresAt}))}:{})},{headers})}catch{return Response.json({error:'Rewards storage is unavailable or campaign configuration needs attention. Reporting and navigation remain wallet-free.'},{status:503,headers})}}
export async function POST(request:Request){const access=auth(request);if(!access)return Response.json({error:'Unauthorized or expired access'},{status:401,headers});let body;try{body=await boundedBody(request);if(!body||typeof body.action!=='string')throw Error();}catch{return Response.json({error:'Invalid rewards request'},{status:400,headers})}
 try{const {service,repo}=await getRewardsContext();if(access.review){if(body.action!=='review'||!['accept','reject'].includes(body.decision)||typeof body.reference!=='string'||typeof body.reason!=='string'||!body.reason.trim()||body.reason.length>2000||!body.reference.trim()||body.reference.length>1000)throw Error('Provide a valid review decision, evidence reference and rationale');const report=await repo.transact(async s=>s.reports[String(body.reportId)]);if(!report)throw Error('Report not found');await service.review(report.id,{station:report.station,category:report.category,asset:report.asset,platform:report.platform,direction:report.direction,condition:report.condition,observedAt:report.observedAt,kind:'moderator',reviewerId:'configured-moderator',decision:body.decision,reference:body.reference,reason:body.reason});return Response.json({accepted:true},{headers})}
 const identity=access.identity!;
 switch(body.action){
 case 'prepare_report':case 'submit_report':{
 if(!body.observation||typeof body.observation!=='object'||Array.isArray(body.observation))throw Error('Provide an observation');
 const parsed=observationInput(body.observation);
 if(parsed.missing.length)throw Error('Please provide: '+parsed.missing.join(', '));
 if(body.action==='prepare_report'){
  const quote=await service.prepareReport(parsed.report,identity);
  return Response.json({funded:quote.funded,amount:quote.provisionalAmount,taskId:quote.taskId,expiresAt:quote.expiresAt,reason:quote.reason},{headers});
 }
 if(!Number.isSafeInteger(body.expectedAmount)||body.expectedAmount<0||typeof body.submissionId!=='string'||!/^[a-f0-9-]{36}$/.test(body.submissionId)||body.confirmed!==true)throw Error('Review the quoted reward and confirm submission');
 const result=await service.submitReport(parsed.report,identity,{requireFunded:body.expectedAmount>0,requireProvisionalAmount:body.expectedAmount,submissionId:body.submissionId});
 return Response.json({id:result.report.id,status:result.report.verificationStatus,amount:result.provisionalAmount},{headers});
 }
 case 'wallet_challenge':{if(typeof body.address!=='string'||body.address.length>64)throw Error('Invalid wallet address');const challenge=await (await getWalletService()).challenge(identity.accountId,body.address);return Response.json({nonce:challenge.id,message:challenge.message,expiresAt:challenge.expiresAt},{headers})}
 case 'wallet_bind':{if(typeof body.nonce!=='string'||typeof body.signature!=='string'||body.signature.length>200)throw Error('Invalid wallet proof');const signature=Buffer.from(body.signature,'base64');if(signature.length!==64)throw Error('Invalid wallet signature');await (await getWalletService()).bind(identity.accountId,body.nonce,bs58.encode(signature));return Response.json({bound:true},{headers})}
 case 'claim':{if(!Number.isSafeInteger(body.expectedAmount)||body.expectedAmount<1||typeof body.expectedWallet!=='string'||!body.expectedWallet.trim()||body.expectedWallet!==body.expectedWallet.trim()||body.expectedWallet.length>64)throw Error('Confirm the payout amount and verified wallet before requesting a payout');const payout=await getPayoutService();const created=await payout.claim(identity.accountId,identity.groupId,{expectedAmount:body.expectedAmount,expectedWallet:body.expectedWallet});const result=await payout.process(created.id);return Response.json({id:result.id,status:result.status,receipt:payoutReceipt(result)},{status:202,headers})}
 case 'cancel_unsigned':{const payout=await getPayoutService();await payout.cancelUnsigned(String(body.payoutId),identity.accountId);return Response.json({cancelled:true},{headers})}
 case 'reconcile':{const p=await repo.transact(async s=>s.payouts[String(body.payoutId)]);if(!p||p.accountId!==identity.accountId)throw Error('Payout not found');const result=await (await getPayoutService()).process(p.id);return Response.json({id:result.id,status:result.status,receipt:payoutReceipt(result)},{headers})}
 case 'appeal':{const report=await repo.transact(async s=>s.reports[String(body.reportId)]);if(!report||report.accountId!==identity.accountId)throw Error('Report not found');if(typeof body.reason!=='string'||body.reason.length>2000)throw Error('Provide a review reason');await service.dispute(report.id,identity,body.reason);return Response.json({requested:true},{headers})}
 default:throw Error('Unknown rewards action');
 }
 }catch(error){return Response.json({error:error instanceof Error?error.message:'Rewards action failed'},{status:400,headers})}
}
